baseURL = "http://boulangerie-croissy-beaubourg.org/"
languageCode = "fr-FR"
title = "Boulangerie Croissy Beaubourg"
theme ="hugo-theme-massively-master"

# [params]
  # set below parameter to define a favicon
  # favicon = "favicon.ico"

# Below parameters can be set to override default post settings
# [params.posts]
#     foldername = "post"
#     pagesize = "6"
#     featuredpost = "true"

[languages]
[languages.fr]
  languageName = "French"
# [languages.es]
#   languageName = "French"
#   title = "Massively - Versión French"
#[languages.fr]
#  languageName = "Français"
#  title = "Massively - Version Française"